# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-16 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('mobilenumber', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('address', models.TextField()),
                ('first_name', models.CharField(max_length=20)),
                ('email_verfied', models.BooleanField(default=False)),
                ('last_name', models.CharField(max_length=10)),
            ],
            options={
                'indexes': [],
                'abstract': False,
            },
        ),
    ]
