# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-02 13:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='email_verfied',
        ),
        migrations.AddField(
            model_name='myuser',
            name='nationality',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='mobilenumber',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '999999999'. 10 digits allowed.", regex=b'^\\d{10}$')]),
        ),
    ]
