# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-04 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0003_auto_20161104_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nationality',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
