# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-04 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0004_auto_20161104_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_college',
            field=models.BooleanField(default=False),
        ),
    ]
