# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-07 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0005_myuser_is_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='programme',
            field=models.CharField(choices=[(b'Btech', b'Btech'), (b'Mtech', b'Mtech'), (b'Phd', b'Phd')], default=b'Btech', max_length=5),
        ),
        migrations.AddField(
            model_name='myuser',
            name='subject',
            field=models.CharField(choices=[(b'CS', b'CS'), (b'EE', b'EE'), (b'EC', b'EC'), (b'MC', b'MC'), (b'CE', b'CE'), (b'CV', b'CV'), (b'BM', b'BM'), (b'PH', b'PH'), (b'MT', b'MT')], default=b'CS', max_length=2),
        ),
    ]
